[font]
size = 10

[font.bold]
family = "Comic Code Ligatures"

[font.bold_italic]
family = "Comic Code Ligatures"

[font.italic]
family = "Comic Code Ligatures"

[font.normal]
family = "Comic Code Ligatures"
